[package]
name = "screen-painter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "Screen-Painter"
path = "src/main.rs"

[dependencies]
eframe = "=0.21.0"
